name: Build FreeBSD Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build with PyInstaller
      run: pyinstaller --onefile webssh/main.py
    
    - name: Install qemu-user-static
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static
    
    - name: Build FreeBSD executable
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
          freebsd/freebsd-release:13.1 \
          sh -c "pkg install -y python3 py38-pip && \
                 pip install -r requirements.txt && \
                 pip install pyinstaller && \
                 pyinstaller --onefile webssh/main.py"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: webssh-freebsd
        path: dist/main
